---
title: "Constructing Bad Men"
subtitle: "Literary Myths and Protectionist Masculinity"
author: "Jamie Pantazi Esmond"
date: "December 5, 2018"
date-format: "long"
format: 
  html: 
    toc: true
    theme: custom.scss
    fig-cap-location: "top"
    tbl-cap-location: "top"
    title-block-banner: true
    title-block-banner-color: "#744FC6"
    fig-align: "center"
---

# Introduction

In the 2008 film, Iron Man, the opening scene showed the hero, Tony Stark, in a US military convoy that is attacked by unseen aggressors. As Tony Stark is running for cover he sees an explosive with his own name about to detonate; he runs for cover but is captured by men who can only be heard speaking an indistinct Middle Eastern language. The movie goes on to show who Tony Stark was before his abduction, a patriot, an innovator, a weapons engineer, an extremely wealthy man in charge of a large company. Tony Stark's character embodies an ideal American archetype, the self-made, rich, attractive, masculine, white man. He is captured by Arab men, identified as terrorists in the movie, and held hostage and forced to build weapons for the terrorist group to use against US forces. Instead he uses his elite skills to build a device that not only saves his own life from the shrapnel in his chest, but also powers his first Iron Man suit with which he escapes and goes on to protect the US and then the world from various threats. Iron Man uses the threat of non-American, non-white aggressors, in the form of militant rogue Arab men, to demonstrate Tony Stark's ability to escape (with the aid of a fellow captive, a contrasting Arab man who martyrs himself in the escape) and return to neutralize the threat entirely.

In the late twentieth and early twenty-first century, Middle Eastern Muslim men and Latin American drug lords have been portrayed as a primary threat against the US and its citizens, both in administrative rhetoric and mass entertainment media. Since the USSR began posing less of a threat against the United States in the 1980s, action movies such as True Lies (1994), Delta Force 2: The Colombian Connection (1990), and the popular television show 24 (2001-2014) have reinforced the myth of a foreign threat of dangerous bad men. It was not only film and mass media that perpetuated this myth, it is also present in the legal system, especially following the attack on the World Trade Center on September 11, 2001. The USA PATRIOT (Uniting and Strengthening America by Providing Appropriate Tools Required to Intercept and Obstruct Terrorism) Act (2001) was an anti-terrorist act of congress and signed by George W. Bush in the wake of the September 11 attacks. The act was designed to lessen the judicial and executive oversight of the surveillance and detention of individuals and organizations suspected of terrorist activities. Almost forty years after the Civil Rights Act guaranteed rights for black citizens and over two centuries after the ratification of the United States constitution, the USA PATRIOT Act and much of the mass media are still positioning non-white or non-American men as a threat to US citizens and especially to American masculinity. "Good" men must be able to protect their families or country from "bad" men; as Iris Marion Young argues, "Good men can only appear in their goodness if we assume that lurking outside the warm familial walls are aggressors who wish to attack them." In the case of Iron Man and the USA PATRIOT Act, the "bad" men are Arab men believed to be Islamic extremists who want to destroy the American national identity, if not the country as a whole.

This threat is not a new idea. Since the American identity began to form in the minds of white settler colonialists, this protectionist model of masculinity has been present in media. Media plays an important role in maintaining systems of white male supremacy as it is enables average citizens who consume media to relate to the issues and conflicts presented. As a distinctly American hero began to emerge in the arts of the new United States, the audience, whether readers of cheap novels or patrons of fine art, began to unify behind an ideal man that represented protection against common threats, both from outside and within, in the form of men of color. Though this ideal American masculinity that emerged certainly did not represent all men, but it provided a widespread common identity that much of the white male power structure could relate and use to justify legal and extralegal violence. To understand how racial violence has persisted, it is important to analyze the roots of its implementation, one of which is mass media.

The origins of American masculinity are most distinct in the years leading up to the Revolutionary War because the settler colonialist who had fought in the Seven Years War gained a sense of identity separate from the British through combat. War has often been a place where men build solidarity through combat against a common enemy. The first references to "Americans" as a word to refer to European settlers occurred during the Seven Years war. Most of these men were born in the colonies and believed they were fighting for their land and nation, not necessarily Britain's land; the seeds of independence were sewn in this conflict, along with the seeds of a distinctly American identity.

The literature and visual art following independence expressed these specifically American ideals clearly through popular historical fiction of the time. During the Constitutional era and throughout the nineteenth century, Indigenous men were portrayed in fiction and visual art as savage, uncivilized, and unable to control their animalist urges, such as someone who would attack a family and kidnap young women. The Frontier officially closed in 1890, and the threat considered mostly neutralized, as the image of the "vanishing Indian" came to replace captive narratives. However, the simultaneous end of Reconstruction in the US South supported another invented threat that took its place in the foreground of popular fiction, the mythical black rapist. The American national identity, for as long as it has existed, has based itself on white masculinity and its superiority; in order for white men to consider themselves part of the true American identity, there must be men who are inferior and therefore a threat. Today, a primary target is the outside threat of Arab or Muslim men and Latin American immigrants, but it is a theme that began with origins of the American ideology. This artistic theme has continued throughout US history, replacing each archetypal aggressor as needed; literature, art, and other forms of mass media have influenced the motives behind systematic racial violence, both on institutional and individual levels, in a more subliminal but highly influential way.

# Origins of American Identity and Masculinity

The United States constitution was ratified in 1788 solidifying a national structure built on a single American identity. Even among the wealth disparity of yeoman farmers and privileged elite, whiteness unified these otherwise vastly different men. The seeds of an American identity emerged in the decades proceeding the Revolutionary War, following the Seven Years War. In North America men of British heritage, but largely born in the colonies, had fought the French over land disputes. It was through this conflict that these settler colonialists began to form an identity different than that of British subjects. Aside from laying the groundwork for the forthcoming Revolutionary War, this shift toward a national identity also worked to solidify a particularly American brand of masculinity rooted in white male supremacy. Landowning elite had little else in common with poor landless workers besides race. Racial superiority and white masculinity were the basis on which the national American identity was built; in addition to gender superiority that had characterized masculinity in Europe, the white men with the greatest influence in the newly formed United States considered themselves not only superior to women but to non-white men. White men without influence were inclined to align themselves with this dominant identity because it meant that they were also superior to others, if not in class, then at least in race.

Because of the various backgrounds of settler-colonists by the end of the eighteenth century, the American identity was based on more than nationality, or nation of origin. Whiteness was the distinguishing factor that was collectively shared by the men who considered themselves founders of the United States of America; African and Indigenous people along with foreigners were considered other, and thus white men felt a sense of commonality in being white. The solidarity fostered by the commonality of whiteness was essential in forming a unified national identity.  The new nation needed to differentiate its identity from that of a British or European identity, through white supremacy early Americans, as defined by this identity, considered themselves superior to others consider savage or foreign; a newspaper in 1819 wrote, “The United States…might the more readily acquire dominion over the savage mind, which would eradicate the traces of British influence.” 

While the legal system and its language has often been obvious in withholding rights from non-white and non-male citizens from the beginning, the mentality of white male supremacy was reinforced and ingrained in people’s patriotic identity through representation in art and literature. More so than simply an elite class declaring their superiority and enforcing it through bias laws and systems, representation gave the average citizen, including those suffering from such subjugation, a reason to believe it was warranted. As art is influenced by life, it also influences life; in the case of American masculinity, art has been crucial in demonizing “others” and creating a mythical threat from which white men must protect women, the sovereignty of their nation, and their national identity.

# Representation of Indigenous Men

As early as the 1790s, novels portraying Indigenous men as savages with animalist urges began to appear. The History of Maria Kittle (1797) tells the story of a kidnapped girl and a "demonic savage." The story told the history of the new nation, complete with emerging stereotypes that reinforced the white male American as a hero in the service of protection and dangerous Indigenous men as a threat to the new American ideal. The women's characters were easily used as a metaphor for the land and citizens in relation to the government; Men, the government, must protect women, the citizens, and to do so they must be superior to them. Though not particularly famous or critically acclaimed in and of itself, The History of Maria Kittle sparked an archetype that would be prolific for the next century and a half.

Visual art in the early nineteenth century reinforced and romanticized heroic white men saving white women from these imagined beastly men. In 1804, John Vanderlyn painted The Murder of Jane McCrea (below). The painting depicts an attack of a white woman by two Indigenous men, shown as larger and stronger than realistic, and a white man in the distance running to her rescue. The woman is shown with pale skin and her breast somewhat exposed, giving her a sex appeal in addition to the brutal nature of the attack. This image is representative of the captive narrative and the sensuality (or sexuality) of women, portrayed as nothing more than an object to be rescued. The man in the distance appears to be a well-dressed white man; this was most likely a comment on how upper-class men had become soft and unable to protect women from these threats. The painting called on strong, able men to combat the painted threat of beastlike attackers. The duality of wealthy self-made men in the cities and the strong, rugged frontiersmen was portrayed by the painting and perpetuated a paradoxical "playing Indian" trend. White men wanted to conquer both the land and the identity of Native men; "playing Indian" was another way that American masculinity formed and is evidenced by the colonists who dressed as Indians during the Boston Tea Party and James Fenimore Cooper's famous character, Hawkeye, in Last of the Mohicans (1826).

As the United States expanded its territory westward throughout the nineteenth century, justification for the conquest continued to be reinforced by literature. During the second half of the nineteenth century, dime novels became popular. With higher literacy rates and the innovation of the newsstand, these simple narratives were easily accessible across class and cultural lines. Mass production and distribution of these novels gave rise to the Western genre in popular culture as it depicted and romanticized western expansion and conquest. The Western genre has always been a clear representation of the conflict between civilization, as it was understood by white Americans, and the frontier, an untamed and outlaw place; the hero, or cowboy, became the embodiment of both of these concepts and as a white man, his character works to resolve the conflict between the two sides. Westerns also often take place within a historical moment instead of the contemporary period, thus influencing the public historical memory of the past. Instead of the brutal battles and massacres that occurred with the westward expansion of the US, the popular memory became one of heroism, masculinity, and progress in the minds of white citizens.

One of the first and most popular of these dime novels that depicted the heroism embedded in the historical memory of the frontier was Edward S. Ellis' Seth Jones: Or, The Captives of the Frontier (1860). The story of Seth Jones was about a mysterious, manly stranger who came upon a woodsman's home, Haverland, on the frontier of New York in the aftermath of the Revolutionary War. Immediately he was enamored with his daughter, Ina, and when the house was attacked by Mohawks, she was taken. Seth met Graham, to whom Ina is betrothed, when he returned to find the house burned, and they set out together to track her captors. When Seth was accidently swept up with the Mohawks caravan, he used his wits to avoid execution, and Graham escaped capture by "shooting ahead with almost superhuman velocity. He glanced back and saw his followers, and they seemed almost standing still, so rapidly did he leave them behind." This display of competition between the white man and the Mohawks perusing him is another example of the white men's need to conquer both the land and the identity of Indigenous men; Graham proved he was superior to his pursuers in physically as well as racially. He later crossed paths with Ina's father and Haldidge, an experienced hunter whose family was murdered by Indians. Together they tracked the Mohawks by following Seth's clues and rescue him and Ina. After the rescue was completed, the Mohawks tracked them as they attempted escape back through the frontier to their settled town, but the white characters outsmart their pursuers at every turn.

Full of literary tropes to exaggerate "good" white men and "bad" Indian men, Seth Jones painted a clear picture of the sentiment among readers regarding patriotism and white men settling the Frontier. Without having to explicitly say it, the novel and many others like it implied the very motivations that justified genocide and conquest. Depicting the massacre of Mohawks in the novel (though almost never referred to as such, usually the more dehumanizing "savage") as a just and moral deed on behalf of an innocent young woman works within the national narrative of white male superiority. The novel gave the contrast of good and bad between white and non-white in addition to the protection of a woman, who is continuously referred to as helpless or unable to take care of herself. When she was returned to her father she "said no more but shrunk beneath his sheltering form, believing that his strong arm was capable of protecting her against any foe, however formidable." Ina's character could have been replaced with a chest of gold and the storyline would not have been changed; women were a symbol for the land to be conquered and protected, they were props, albeit valuable props, but unable to hold their own agency. Her rescuers observed that the captors understood her value as "it was plain they had some fears of pursuit; and to guard their treasure, a number had left them at a favorable point."

Seth Jones and other books like it were praised in newspaper reviews and advertisements. The captive narrative was a favorite in the dime novel Westerns, and these novels remained best sellers until the end of the century. White women's characters provided a clear and valuable object worth protecting for the white male heroes; women in these novels were overtly objectified and, in many instances, used as a metaphor for the frontier itself. Dana Nelson argues that within Westerns, "Men's criminal dramas are mapped across female bodies." In Seth Jones, like many other novels of the genre, the woman captured was the only woman named, she had almost no dialogue, and was seen only as an object to be recovered for marriage to one of her rescuers. Women who enjoyed these novels may have overlooked these over simplifications and subjugation of their gender because of the narrative of heroes defeating a threat to their purity, adding to racial prejudices of an imagined danger.

# Vanishing Threats and Reconstruction

The Census Bureau officially closed the Frontier in 1890.  The United States had declared dominance across the continent. Conquering the West led to the popularity of the image of “vanishing Indians” in the last decades of the nineteenth century that would last through most of the twentieth century, especially through film.  According to the national narrative, the Indigenous population had vanished, and the threat to white masculinity and white women was vanished along with it. Even the language used to describe the conquest of the West, for example “Manifest Destiny,” justified and diminished the aggression of white settlers; use of the passive word “vanished” implied that Indigenous communities simply ceased to exist instead of more active verbs like slaughtered, attacked, and massacred that perhaps more accurately describe settler colonial expansion. The language is important to the historical memory, and it also reinforced the necessity for a new active threat for American men to prove masculinity, since whiteness can only be a superior race if there is an inferior race, and protectionist masculinity can only protect if there is a threat to protect against.


America Progress (below) was painted by John Gast in 1872 depicting westward expansion with "progress" personified by a fair skinned woman leading white men west, bringing light from the East. Settlers in covered wagons optimistically venture west seeking opportunities; ready to farm and mine the land, as evidenced by the tools carried by the men in the foreground of the painting, these men hoped to make their fortune in the name of progress of the United States. Railroads and telegraph wires symbolized the progress of industry and connectivity spanning across the continent. The light of Lady Progress emanated from the cities and industry of the East and darkness covered the barely clothed Indigenous men and buffalo as they were pushed further west, even off the scene entirely. From right to left, or east to west, the detail of the characters is clearer in the light of Lady Progress, but much less defined on the west edge of the image. White men venturing to the Frontier likened themselves to this imagery and it compelled them to seek heroic manhood within the American identity by carrying out the violence of conquest.

At the time the West was being “won” by white men, black men in the South were experiencing political, economic, and cultural power for the first time in the United States. Though short-lived, Reconstruction following the Civil War gave freed black men opportunities to take institutional power from white men through voting and running for office in the South. While federal troops remained in the formerly Confederate states, the white elite had few avenues for recourse; attempts were made by the Red Shirts and the Ku Klux Klan, but they were short lived in the occupied South.  Directly following the Compromise of 1877, which removed federal presence in the South, southern men started retelling their history to save face in the aftermath of not only military defeat but temporary displacement in the power structures. Without federal troops protecting black men at the polls, white men would terrorize would-be voters and white primaries made it impossible for black men to run for office. While white politicians were retaking their place in legal institutions, artists were reaffirming their authority to do so, primarily though historical fiction that portrayed black men as not only a threat to political power but to another valued possession of white men, white women. 

While minstrel shows, such as those with the Jim Crow character, inspired the segregationist laws that came to be referred to by the same name, authors and performers began to create an imaginary historical memory of southern white men, through literature and the stage, defending white women from barbaric black men with uncontrollable sexual urges. Because of the popularity of these narratives, the fictional historic memory became ingrained in the minds of men who justified violence against black men on the basis of the invented threat. In her book Woman, Race & Class, Angela Davis discusses several historical examples of violence against black men used to avenge alleged attacks against white women; based largely on a fictional historic memory, she asserted that there is the lack of real evidence of black men assaulting white women in significant numbers prior to Reconstruction called into question the accuracy of these retellings. By pointing out the historical discrepancies, she affirmed that these narratives were merely justification for real violent white supremacy. Men like Thomas Dixon and D. W. Griffith, who adapted Dixon's book into the 1915 film Birth of a Nation, essentially rewrote history for popular consumption constructing a fictional threat that served as motivation for real world racial violence. From the resurgence of the Ku Klux Klan to the normalization of violent prejudice, Griffith's film and other narratives like it solidified a foundation for American systems of racial violence.

# Representation of Black Men
       
Throughout the second half of the nineteenth century, newspapers offered sensational reports of black men allegedly attacking white women usually in the context of the man’s brutal punishment. Often, they read more like a justification for the beating or lynching of a black man than a report of sexual assault. Colorful language and exaggerated offenses were common in these reports; one article referred to the man accused as a “demon, in human form.”  One article from the Daily National Intelligencer argued that it was emancipation and radical reform that transformed black men from “an orderly, peaceful, and obedient race” that one could “favorably compare with the peasant in foreign lands.”  It is impossible to say if there is any truth to the accusations against these men, but it is clear from the language that the primary goal of this kind of reporting was to arouse suspicion of black men, especially in the context of their interaction with white women.

Other than these fearmongering reports in the newspapers, a common portrayal of black people occurred through minstrel shows, which depicted caricatures of laziness, foolishness, and simplemindedness.  In contrast to the aggressive stereotypes emerging in newspaper reports, the primary alternative representation was rooted in the pre-emancipation archetype of docile and submissive subordinates. Powerless in essence, black men depicted in these shows reinforced the idea that black men knew their place under enslavement, and their newfound freedom would engender unrestricted aspirations for power over white men and especially white women. This duality created, within the dominant American identity, only two options for the perception of black men in the minds of white men who consumed such media: submissive or aggressive, a tool or a threat. 

Beyond sensational news reporting in the various newspapers and contrasting minstrel shows, the threatening image of black men began to emerge in literature after Reconstruction ended. During Reconstruction, white power structures used overt means to show their disapproval of black men participating in political and economic arenas, but with federal occupation, their efforts were not sustainable. In the decades after federal troops left the South, white men seem to have feared black men and their newfound limited freedom. In 1905, Thomas Dixon released his alternative history of this sensitive period for white men that gave glory back to them and renewed fears of miscegenation. As both a series of novels and a play, in 1905, The Clansman was widely appreciated by the public across the South. Newspaper reviews following the play's first year of performance were generally laudable. Although many audiences enjoyed the glorious re-enactment of a more favorable history for white Southerners, critics began to call out the inaccuracies of the play and worried it would incite violence against black citizens. During a performance in Atlanta in 1905, white audience members were riled up by the portrayal of a young white woman choosing death over disgrace at the hands of a black man, and some were worried that the play my incite real violence as the audience cheered for the death of Gus, the fictional would-be rapist, when he was captured by the Ku Klux Klan. In fact, just days after the brutal race riots in Atlanta, the city council in Montgomery, Alabama, called on the mayor to ban the play as reported with the headline "'The Clansman' Not Wanted Here," and Montgomery leaders blamed the play for the Atlanta's "present race troubles." The newspapers reported similar allegations against black men in the days and months leading up to the violence that erupted in September 1906, which may have been embellished as a result of the dramatic depiction of such assaults in the play.

Sensational newspaper articles, literature, and minstrel shows were obvious channels for sentiments of white male supremacy, and at the dawn of the new century, film became a crucial avenue for mass distribution of any message. However, early films were considered more of an attraction than a narrative art form. Many films were short, often single shots or scenes, and many viewers were more interested in the feat of the moving picture than anything that picture might be portraying. D. W. Griffith aimed to change that; still praised today as an indispensable innovator in the medium of film, he is attributed with developing the formal cinematic techniques that perpetuate storytelling in a way that is unique to the screen. His film Birth of a Nation, based on Dixon's work, was the first blockbuster in American cinematic history; as the first three hour length film shown in regular theaters and the first film screened at the White House, Griffith revolutionized the film industry and brought his narrative to more people than ever before. Philip B. Heymann and Melvyn Stokes, in their appropriately titled book D. W. Griffith's the Birth of a Nation: A History of the Most Controversial Motion Picture of All Time, effectively sum up the film's message, "To save Southern whites, and especially Southern women, from this dangerous situation, a new organization emerged: the white-sheeted 'knights' of the Ku Klux Klan. Using considerable violence, gallant Klansmen eventually managed to subdue the aggressive Southern blacks, and white supremacy was restored."

Much like Dixon's play, many people, especially the NAACP (National Association for the Advancement of Colored People) were concerned about the racist content of the film and the propensity for it to incite real violence. These fears were not unfounded. As the historic memory of the black rapist was solidified in the minds of white men of all classes, the resurgence of the Ku Klux Klan was directly inspired by Griffith's film. Recruitment materials and propaganda for the Ku Klux Klan incorporated the same images used for promotion of the film. In the century that followed the film's release, film and social historians have published extensive discourse about its importance in early cinema and the racist sentiments it proliferated. Hailed as one of the most controversial films of all time, Birth of a Nation propelled not only the budding film industry into the new century, but also signified the mass influence the medium could have on the public.

# Conclusion

Politically, Birth of a Nation inspired the resurgence of the Ku Klux Klan and doubled down on Jim Crow and anti-miscegenation rhetoric, but it also demonstrated a new medium for distributing models of white male supremacy as an American identity, perhaps more effectively than ever before. Over the next century, film, as literature and art had in the previous century, has played an important role in maintaining unity within a dominant American Identity. The revitalized Western genre found a very profitable home in cinema during the mid-twentieth century, renewing old captive narratives and pitting "cowboys and Indians" against each other once again. Black face and devastating racial stereotypes were common throughout the first half of the twentieth century, and they continued to lesser degrees as more people of color gained access to the industry to represent themselves. Today, film, along with literature and other mediums, continue to use constructed archetypes to maintain and perpetuate racial stereotypes that directly and indirectly influence real physical violence against people of color, especially men. A good American man requires a bad man for contrast, and mass media has consistently constructed that bad man and delivered him to the homes of ordinary people as if he were real. 

# Bibliography

## Primary Sources

24. Created by Robert Cochran, Joel Surnow. USA: 20th Century Fox Television, 2001-2014. Birth of a Nation. Directed by D. W. Griffith. Santa Monica, CA: Epoch Producing Corporation, 1915. Bleecker, Ann Eliza. The History of Maria Kittle. Hartford: Elisha Babcook, 1797. Reprinted New York: Garland Publishing, 1978.

Cooper, James Fenimore. The Last of the Mohicans: A Narrative of 1757. Philadelphia: H.C. Carey & I. Lea, 1826.

Delta Force 2: The Colombian Connection. Directed by Aaron Norris. USA: Cannon Films, 1990.

Dixon, Thomas. The Clansman: An American Drama: From His Two Famous Novels: The Leopards Spots and the Clansman: Presented by the Southern Amusement Co. New York: American News, 1905.

Dixon, Thomas. The Clansman: An Historical Romance of the Ku Klux Klan. New York: Grosset & Dunlap, 1905.

Ellis, Edward Sylvester. Seth Jones: Or, The Captives of the Frontier. New York: Beadle and Adams, 1860.

Gast, John. American Progress. 1872. Chromolithograph published by George A, Crofutt. Prints and Photographs Division, Library of Congress. https://picturinghistory.gc.cuny.edu/john-gast-american-progress-1872/

Iron Man. Directed by Jon Favreau. USA: Paramount / Marvel Studios, 2008.

True Lies. Directed by James Cameron. USA: Twentieth Century Fox, 1994.

United States. Census Office. 11th Census, 1890. Compendium of the Eleventh Census: 1890. By Robert P. Porter. Washington, DC: Govt. Print. Off., 1892.

Vanderlyn, John. The Murder of Jane McCrea. 1804. Wadsworth Atheneum, Hartford. http://www.19thcenturyart-facos.com/artwork/murder-jane-mccrea

## Newspapers

### Atlanta Constitution

"'The Clansman' Not Wanted Here," The Atlanta Constitution. (Atlanta, Georgia) September 27, 1906.

"'The Clansman' on the Stage," The Atlanta Constitution. (Atlanta, Georgia) August 13, 1905.

"The Hissing of the 'Clansman'," The Atlanta Constitution. (Atlanta, Georgia) October 22, 1905.

"Tom Dixon Talks of the Clansman," The Atlanta Constitution. (Atlanta, Georgia) October 29, 1905.

### Daily National Intelligencer

"Generalo Cox, candidate of the Republican party for Governor of Ohio, in reply to a committee, writes a striking letter about the problem of the black race." Daily National Intelligencer (Washington, DC), August 04, 1865.

"Insults and Outrages upon the Women of the South." Daily National Intelligencer. (Washington, DC) October 06, 1868.

"The Negro as Developed by Radical Policy." Daily National Intelligencer (Washington, DC), September 26, 1868

"Western Scenery." Daily National Intelligencer. (Washington, DC) March 08, 1819.

### Other Newspapers:

"Beadle's Dime Novels." Frank Leslie's Illustrated Newspaper (New York, New York) December 8, 1860.

"Burning a Negro Murderer." The Daily Scioto Gazette (Chillicothe, Ohio) August 03, 1853.

"Dime Novels." The Wisconsin State Register. (Portage, Wisconsin) April 26, 1884.

"Literary." The Daily Cleveland Herald. (Cleveland, Ohio) December 07, 1863.

## Secondary Sources

Berkholder, Robert F. The White Man's Indian. New York: Alfred A. Knoff, Inc., 1978.

Davis, Angela. "Rape, Racism, and the Myth of the Black Rapist," Women, Race & Class. New York: Vintage Books, 1981.

Dunbar-Ortiz, Roxanne. An Indigenous Peoples History of the United States. Boston: Beacon Press, 2015.

Godshalk, David Fort. Veiled Visions the 1906 Atlanta Race Riot and the Reshaping of American Race Relations. Chapel Hill: University of North Carolina Press, 2005.

Heymann, Philip B., and Stokes, Melvyn. D. W. Griffith's the Birth of a Nation: A History of the Most Controversial Motion Picture of All Time. Cary: Oxford University Press USA - OSO, 2008.

Lennard, Katherine. "Old Purpose, "New Body": The Birth of a Nation and The Revival Of The Ku Klux Klan." The Journal of the Gilded Age and Progressive Era 14, no. 04 (2015): 616-20.

Macdonald, Andrew, Gina Macdonald, and MaryAnn Sheridan. Shape-shifting: Images of Native Americans in Recent Popular Fiction. Westport, CT: Greenwood Press, 2000.

Nelson, Dana D. National Manhood: Capitalist Citizenship and the Imagined Fraternity of White Men. Durham: Duke University Press, 1998.

Parsons, Elaine Frantz. "Klan Skepticism and Denial in Reconstruction-Era Public Discourse." Journal of Southern History 77, No. 1 (February 2011), 53--90.

Pilgrim, David. "The Coon Caricature." Ferris State University: Michigan College Campuses in Big Rapids MI, Grand Rapids MI, Off Campus Locations Across Michigan. October 2000. https://www.ferris.edu/jimcrow/coon/

Richardson, Riché. Black Masculinity and the U.S. South: From Uncle Tom to Gangsta. Athens: University of Georgia Press, 2007.

Richardson, Sarah. "As American as Jim Crow." American History 53, no. 1 (April 2018), 52--59.

Urwand, Ben. "The Black Image on the White Screen: Representations of African Americans from the Origins of Cinema to The Birth of a Nation." Journal of American Studies, 52 (2018), 1, 45-64.

Wingo, Rebecca S. "The 'Forgotten Era': Race and Gender in Ann Stephens's Dime Novel Frontier." Frontiers: A Journal of Women Studies. Vol. 38 Issue 3 (2017), 121-140.

Young, Iris Marion. "The Logic of Masculinist Protection: Reflections on the Current Security State." Signs, Vol. 29, No. 1 (Autumn 2003), 1-25.
